captadores/urls.py
from django.urls import path
from . import views

app_name = 'captadores'

urlpatterns =[ 

    path('', views.home, name = 'home'),
    path('home2', views.home2, name = 'home2'),
    path('form_captador', views.form_captador, name = 'form_captador'),
    path('criar_captador', views.criar_captador, name = 'criar_captador'),
    path('lista_captadores', views.lista_captadores, name = 'lista_captadores')

    
]

django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('captadores.urls'))
]

captadores/models.py
from django.db import models
class Captador(models.Model):

    marca = models.CharField(max_length=30)
    bobina = models.CharField(max_length=9)
    instrumento = models.CharField(max_length=10)

    def __str__(self):
        return self.marca 

captadores/forms.py
from dataclasses import fields
from django import forms
from .models import Captador

class CaptadorForm(forms.ModelForm):
    class Meta:
        model = Captador
        fields = "__all__"
        # exclude = ('marca',)

captadores/views.py
from audioop import reverse
from django.http import HttpResponse
from django.shortcuts import render
from datetime import datetime
from .models import Captador
from .forms import CaptadorForm

# Create your views here.
def home (request):
    captadores = Captador.objects.all()
    return HttpResponse('ok', status = 200)

def home2 (request):
    return render(request, 'home2.html', {'name': 'Leandro', 'time': str(datetime.now())})

def form_captador(request):
    form = CaptadorForm()
    return render(request, 'form_captador.html', {'form': form})

# create a new Captador
def criar_captador(request):
    if request.method == 'POST':
        marca = request.POST.get('marca')
        bobina = request.POST['bobina']
        instrumento = request.POST['instrumento']

        captador = Captador()
        captador.marca = marca
        captador.bobina = bobina
        captador.instrumento = instrumento
        captador.save()
        return render(request, 'sucesso_criacao_captador.html', locals())

#read captadores 

def lista_captadores(request):
    bobina = request.GET.get('bobina')
    if bobina is None:
        captadores = Captador.objects.all()
    else:
        captadores = Captador.objects.filter(bobina=bobina)

    return render(request, 'lista_captadores.html', locals())

captadores/templates/form_captador.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar Captador</title>
</head>
<body>
    <form method="POST" action="{% url 'captadores:criar_captador'%}"> 
        {% csrf_token %}
        {{form.as_p}} 
        <button class="btn btn-primary" type = 'submit'> Submit </button>
    </form>
    
</body>
</html>

captadores/templates/home2.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Exemple</title>
</head>
<body>
 
    <h1>Olá, meu nome é {{name}} </h1>
    <h3> {{time}}</h3>
    <video autoplay loop muted>
        <source src="http://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">
    </video>
    <video autoplay loop muted>
        <source src="http://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">
    </video>
    <video autoplay loop muted>
        <source src="http://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">
    </video>
    <video autoplay loop muted>
        <source src="http://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">
    </video>
    
    <style>

        body {
            margin: 0px;
            background-color: black; 
            color: white;
          }
          video {
            width: 50%;
            float: left;
          }

    </style>        
</body>
</html>

captadores/templates/lista_captadores.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista Captadores</title>
</head>
<body>

    <table>
        <thead>
            <tr>
            <th>Marca</th>
            <th>Bobina</th>
            <th>Instrumento</th>
            </tr>
        </thead>
        
        <tbody>
            {% for captador in captadores %}
            <tr>
                <td>{{captador.marca}}</td>
                <td>{{captador.bobina}}</td>
                <td>{{captador.instrumento}}</td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
    
</body>
</html>

captadores/templates/sucesso_criacao_captador.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SucessoCriacaoCaptador</title>
</head>
<body>
    <h1>Captador Criado com Sucesso</h1>
    <p><h3>Marca:</h3>{{marca}}</p>
    <p><h3>Tipo de bobina:</h3>{{bobina}}</p>
    <p><h3>Instrumento:</h3>{{instrumento}}</p>

</body>
</html>